### ISSUE TITLE
error

### ISSUE THREAD

**Issue by darkanalytica1** [gotr00t0day/Gsec#2]
[+] - /bin/sh: 1: nuclei: not found                                                
                                                                                   
Traceback (most recent call last):                                                 
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen                                                                               
    httplib_response = self._make_request(                                         
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 450, in _make_request                                                                         
    six.raise_from(e, None)                                                        
  File "<string>", line 3, in raise_from                                           
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request                                                                         
    httplib_response = conn.getresponse()                                          
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse             
    response.begin()                                                               
  File "/usr/lib/python3.10/http/client.py", line 318, in begin                    
    version, status, reason = self._read_status()                                  
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status             
    raise RemoteDisconnected("Remote end closed connection without"                
http.client.RemoteDisconnected: Remote end closed connection without response      
                                                                                   
During handling of the above exception, another exception occurred:                
                                                                                   
Traceback (most recent call last):                                                 
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send    
    resp = conn.urlopen(                                                           
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 786, in urlopen                                                                               
    retries = retries.increment(                                                   
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 550, in increment                                                                                 
    raise six.reraise(type(error), error, _stacktrace)                             
  File "/usr/lib/python3/dist-packages/six.py", line 718, in reraise               
    raise value.with_traceback(tb)                                                 
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen                                                                               
    httplib_response = self._make_request(                                         
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 450, in _make_request                                                                         
    six.raise_from(e, None)                                                        
  File "<string>", line 3, in raise_from                                           
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request                                                                         
    httplib_response = conn.getresponse()                                          
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse             
    response.begin()                                                               
  File "/usr/lib/python3.10/http/client.py", line 318, in begin                    
    version, status, reason = self._read_status()                                  
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status             
    raise RemoteDisconnected("Remote end closed connection without"                
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))                                        
                                                                                   
During handling of the above exception, another exception occurred:                
                                                                                   
Traceback (most recent call last):                                                 
  File "/home/kali/Gsec/gsec.py", line 97, in <module>                             
    shellshock.shellshock_scan(args.target)                                        
  File "/home/kali/Gsec/plugins/shellshock.py", line 9, in shellshock_scan         
    res = requests.get(domain, verify=False, headers=header)                       
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get           
    return request('get', url, params=params, **kwargs)                            
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request       
    return session.request(method=method, url=url, **kwargs)                       
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 529, in request 
    resp = self.send(prep, **send_kwargs)                                          
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 645, in send    
    r = adapter.send(request, **kwargs)                                            
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 501, in send    
    raise ConnectionError(err, request=request)                                    
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by gotr00t0day** [comment]
You need to install nuclei, make sure you run python3 install.py :P

**Comment by ev0l3t** [comment]
I keep getting this..
how can I fix it?

Traceback (most recent call last):
  File "/home/ev0l3t/Gsec/gsec.py", line 3, in <module>
    from utils import portscanner, loginscanner, techscanner, cmsscanner, passive_recon
  File "/home/ev0l3t/Gsec/utils/techscanner.py", line 1, in <module>
    from builtwith import builtwith
ModuleNotFoundError: No module named 'builtwith'

**Comment by gotr00t0day** [comment]
You need to install builtwith with pip. pip3 install builtwith. I also added this to requirements.txt so you can just do pip3 install -r requirements.txt

**Comment by darkanalytica1** [comment]
awesome, lemme try it
