### ISSUE TITLE
Cannot run gsec.py

### ISSUE THREAD

**Issue by d4rkhub** [gotr00t0day/Gsec#3]
Traceback (most recent call last):
  File "/Users/host/tools/Gsec/gsec.py", line 2, in <module>
    from modules import fetch_requests, scan, urltoip
ImportError: cannot import name 'scan' from 'modules' (/Users/host/tools/Gsec/modules/__init__.py)

**Comment by gotr00t0day** [comment]
What version of python3 are you using?

**Comment by d4rkhub** [comment]
Oke After I re-install V0.15. I get new issue.

User@Host-MacBook-Pro gsec % python3 gsec.py
Traceback (most recent call last):
  File "/Users/username/tools/Gsec/gsec.py", line 3, in <module>
    from utils import portscanner, loginscanner, techscanner, cmsscanner, passive_recon
  File "/Users/username/tools/Gsec/utils/passive_recon.py", line 2, in <module>
    import whois
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/whois/__init__.py", line 15, in <module>
    from .parser import WhoisEntry
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/whois/parser.py", line 18, in <module>
    from past.builtins import basestring
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/past/builtins/__init__.py", line 43, in <module>
    from past.builtins.noniterators import (filter, map, range, reduce, zip)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/past/builtins/noniterators.py", line 24, in <module>
    from past.types import basestring
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/past/types/__init__.py", line 25, in <module>
    from .oldstr import oldstr
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/past/types/oldstr.py", line 5, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)

**Comment by d4rkhub** [comment]
Oke done.. after re-Install to v0.15 I can run gsec.py.. but I get new issue when scaning..

[+] - Technologies: 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/Users/username/tools/Gsec/gsec.py", line 104, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/username/tools/Gsec/gsec.py", line 90, in main
    robots.robots_scan(args.target)
  File "/Users/username/tools/Gsec/plugins/robots.py", line 15, in robots_scan
    req = urlopen(f"{domain}/robots.txt", data=None)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

**Comment by gotr00t0day** [comment]
If you look at the README file, GSec was only tested for python3.9 until python3.10.4 but it seems is having issues after python3.10.4 , So I suggest to only use any version of python3.9 for now or python3.10.4.

**Comment by gotr00t0day** [comment]
I found a fix for this issue, check if you have certifi installed. "pip install certifi" or "pip3 install certifi" and then do /Applications/Python\ 3.9/Install\ Certificates.command just change 3.9 to 3.10 and it will be fixed.

**Comment by d4rkhub** [comment]
I run "pip3 install certifi" 
Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (2022.9.14)

**Comment by gotr00t0day** [comment]
Yeah, the fix I told you about should fix the problem.

**Comment by d4rkhub** [comment]
Oke thx bro for info, before I upgrade source gsec I can run gsec but today after upgrade source gsec apperas new error

username@host-MacBook-Pro gsec % python3 gsec.py
Traceback (most recent call last):
  File "/Users/username/tools/Gsec/gsec.py", line 3, in <module>
    from utils import portscanner, loginscanner, techscanner, cmsscanner, passive_recon
  File "/Users/username/tools/Gsec/utils/cmsscanner.py", line 4, in <module>
    from plugins import agent_list, versioncheck
ImportError: cannot import name 'versioncheck' from 'plugins' (/Users/username/tools/Gsec/plugins/__init__.py)

**Comment by gotr00t0day** [comment]
Actually I didn't mean to add versioncheck.py to the push request. That's something I'm working on that's gonna be release in a new version.

**Comment by d4rkhub** [comment]
Noted,, thx bro

**Comment by gotr00t0day** [comment]
> Noted,, thx bro

Join my discord, is in the README
