### ISSUE TITLE
Problem Using Gsec on VM Kali Linux

### ISSUE THREAD

**Issue by d4rkhub** [gotr00t0day/Gsec#5]
I have problem when using gsec on kali linux vm, how to resolve it.

┌──(kali㉿kali)-[~/tools/Gsec]
└─$ python3 -V     
Python 3.10.5
                                                                             
┌──(kali㉿kali)-[~/tools/Gsec]
└─$ python3 gsec.py
Traceback (most recent call last):
  File "/home/kali/tools/Gsec/gsec.py", line 5, in <module>
    from vuln_db import hostheader_injection, nuclei_vulns, corsmisconfig, crossdomain, head_vuln
  File "/home/kali/tools/Gsec/vuln_db/nuclei_vulns.py", line 2, in <module>
    from modules import scan, sub_output
ImportError: cannot import name 'sub_output' from 'modules' (/home/kali/tools/Gsec/modules/__init__.py)

**Comment by gotr00t0day** [comment]
> I have problem when using gsec on kali linux vm, how to resolve it.
> 
> ┌──(kali㉿kali)-[~/tools/Gsec] └─$ python3 -V Python 3.10.5
> 
> ┌──(kali㉿kali)-[~/tools/Gsec] └─$ python3 gsec.py Traceback (most recent call last): File "/home/kali/tools/Gsec/gsec.py", line 5, in from vuln_db import hostheader_injection, nuclei_vulns, corsmisconfig, crossdomain, head_vuln File "/home/kali/tools/Gsec/vuln_db/nuclei_vulns.py", line 2, in from modules import scan, sub_output ImportError: cannot import name 'sub_output' from 'modules' (/home/kali/tools/Gsec/modules/**init**.py)

Nice catch, I forgot to add the modules/sub_output.py file, but it's fixed now! Thanks

**Comment by d4rkhub** [comment]
Okay, Case Closed
