### ISSUE TITLE
Tool not able to execute

### ISSUE THREAD

**Issue by Karan321** [gotr00t0day/Gsec#7]
Please help me with this error:

python3 gsec.py                                                                 
Traceback (most recent call last):
  File "/home/karan/tools/Gsec/gsec.py", line 3, in <module>
    from utils import path_traversal, portscanner, loginscanner, techscanner, cmsscanner, passive_recon, crawler
  File "/home/karan/tools/Gsec/utils/passive_recon.py", line 2, in <module>
    import whois
  File "/home/karan/.local/lib/python3.11/site-packages/whois/__init__.py", line 15, in <module>
    from .parser import WhoisEntry
  File "/home/karan/.local/lib/python3.11/site-packages/whois/parser.py", line 18, in <module>
    from past.builtins import basestring
  File "/usr/local/lib/python3.11/dist-packages/future-0.16.0-py3.11.egg/past/builtins/__init__.py", line 43, in <module>
    from past.builtins.noniterators import (filter, map, range, reduce, zip)
  File "/usr/local/lib/python3.11/dist-packages/future-0.16.0-py3.11.egg/past/builtins/noniterators.py", line 24, in <module>
    from past.types import basestring
  File "/usr/local/lib/python3.11/dist-packages/future-0.16.0-py3.11.egg/past/types/__init__.py", line 25, in <module>
    from .oldstr import oldstr
  File "/usr/local/lib/python3.11/dist-packages/future-0.16.0-py3.11.egg/past/types/oldstr.py", line 5, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.11/collections/__init__.py)

**Comment by gotr00t0day** [comment]
Did you install the requirements? **pip3 install -r requirements.txt** and try to run **python3 gsec.py -h**

**Comment by Jonathan-404** [comment]
[@gotr00t0day], please consider the following steps to fix the issues with the requirements.txt file and ensure consistent package versions for the repository:

Remove the existing requirements.txt file from the repository.

Open the console and navigate to the repository's root directory.

Execute the following command in the console:

`pip freeze >> requirements.txt`

This command will generate a new requirements.txt file that contains the packages and their versions currently being used in your environment.

Commit and push the updated requirements.txt file to the repository.

By following these steps, anyone who clones or uses this repository will have access to the same package versions as you, reducing compatibility issues and ensuring a consistent development environment.

Please let me know if you need any further assistance or have any questions.

Thank you.
